### ISSUE TITLE
Add lint rules

### ISSUE THREAD

**Issue by nicks101** [smaranjitghose/DocLense#152]
There are several options to add `lint rules`. 
We can use a community package [lint](https://pub.dev/packages/lint).  It is customizable and so we can edit any rule as we like.

**Comment by nicks101** [comment]
I'd like to work on this issue under GSSOC'21 if it's okay.

**Comment by deeppatel23** [comment]
As a GSSOC'21 Participant, I would like to work on this issue.

**Comment by smaranjitghose** [comment]
> There are several options to add `lint rules`.
> We can use a community package [lint](https://pub.dev/packages/lint). It is customizable and so we can edit any rule as we like.

Could you search for an option to integrate this as GitHub Action workflow please?

**Comment by smaranjitghose** [comment]
> As a GSSOC'21 Participant, I would like to work on this issue.

Other than issues raised by project maintainers, all other issues would be assigned by default to the participant who raises it (after evaluation)

**Comment by nicks101** [comment]
> > There are several options to add `lint rules`.
> > We can use a community package [lint](https://pub.dev/packages/lint). It is customizable and so we can edit any rule as we like.
> 
> Could you search for an option to integrate this as GitHub Action workflow please?

On it.

**Comment by nicks101** [comment]
For lint, we can have Github Action that'll run static dart linter test
1.  without providing any custom lint rules.
2.  with custom lint rules `(analysis_options.yaml file)`

Below is the basic workflow to test lint.

```
name: lint check
on: [pull_request]
jobs:
  lint:
    name: lint test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.9.1+hotfix.2'
          channel: 'stable'
      - name: Install packages
        run: |
          cd ./DocLense
          flutter pub get
      - name: Lint
        run: |
          cd ./DocLense
          flutter analyze
```

References
[ci yaml code](https://medium.com/@jacksonz666/guard-your-open-sourced-flutter-app-with-github-actions-824cc4d9844) 

I found this Github Action as well specifically to [Analyze Dart](https://github.com/zgosalvez/github-actions-analyze-dart) (though it's new).

Let me know the direction to move forward in.

Just for thought, we can have GitHub Actions for unit and integration tests as well similar to lint ones.
